// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SimpleBlog.Data.Blog;
using System;

namespace SimpleBlog.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20180518161858_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("SimpleBlog.Data.Blog.Comment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Author");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<string>("PostId");

                    b.HasKey("Id");

                    b.ToTable("blog_comment");
                });

            modelBuilder.Entity("SimpleBlog.Data.Blog.Configuration", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("blog_configuration");
                });

            modelBuilder.Entity("SimpleBlog.Data.Blog.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Author");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<string>("Excerpt");

                    b.Property<string>("SeoName");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("blog_post");
                });
#pragma warning restore 612, 618
        }
    }
}
