// <auto-generated />
using DemoSwastikaHeart.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DemoSwastikaHeart.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoSwastikaHeart.Models.Comment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Author");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<string>("PostId");

                    b.HasKey("Id");

                    b.ToTable("blog_comment");
                });

            modelBuilder.Entity("DemoSwastikaHeart.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedDateUTC");

                    b.Property<string>("Excerpt");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("blog_post");
                });
#pragma warning restore 612, 618
        }
    }
}
